version: "3.8"

services:
    web:
        build: .
        container_name: chatbot-web
        command: flask run --host=0.0.0.0 --port=5555
        networks:
            - app-network
        ports:
            - "5555:5555"
        depends_on:
            - postgres
        restart: always
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/venv
    postgres:
        image: postgres:latest
        networks:
            - app-network
        env_file:
            - .env
        ports:
            - "54320:5432"
        volumes:
            - postgres_chat:/var/lib/postgresql/data

volumes:
    postgres_chat:

networks:
    app-network: