"""empty message

Revision ID: 525f9cd2acd9
Revises: 079eb5c4dc0c
Create Date: 2024-06-06 10:33:55.623659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525f9cd2acd9'
down_revision = '079eb5c4dc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('world_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sub_content', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_content', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('world_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
